[package]
name = "ci-experiments-rust"
version = "0.1.0"
authors = ["Yarrow Angelweed <yarrow.angelweed@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
